[package]
name = "newsense-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
feed-rs = "2.3.1"
reqwest = "0.12.12"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
